### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1	

### PR DESCRIPTION
**Pull request by rmax**

### CODE REVIEW

**Comment by jakirkham** [comment]
Which version of `conda-smithy` did you use? Guessing 1.7.0. Could you please try with 2.0.1 unless there is a reason not to?

**Comment by rmax** [comment]
@jakirkham done!

**Review by jakirkham — APPROVED** [review]

**Comment by rmax** [comment]
ping @conda-forge/core

**Comment by ocefpaf** [comment]
> ping @conda-forge/core

I recommend you adding yourself as a maintainer if you are interested in this package.

**Comment by rmax** [comment]
@ocefpaf No need, I just noticed the win+py27 packages were missing, packages I needed for other recipe.

**Pull request merged**
