### PR TITLE
Increase build number to trigger new builds on windows.

### PR DESCRIPTION
**Pull request by rmax**
Windows' py27 packages are missing.

### CODE REVIEW

**Comment by jakirkham** [comment]
No need to bump the build number. Will restart AppVeyor.

**Comment by jakirkham** [comment]
Have restarted. Feel free to close this. Though if you wish to be a maintainer, feel free to submit a PR adding yourself and will be happy to merge. Note that adding `[skip ci]` to the commit message and leaving the build number alone are wholly appropriate in that case.

**Comment by rmax** [comment]
Hey @jakirkham thanks for the intervention. I just needed the win-py27 packages for #2448

**Comment by rmax** [comment]
All win builds failed. Does it need a re-render? https://ci.appveyor.com/project/conda-forge/pathlib-feedstock/build/job/7t5uaysooeca31xf

**Comment by jakirkham** [comment]
Looks like it. Could you please send a re-rendering PR, @rolando?

**Comment by rmax** [comment]
Here https://github.com/conda-forge/pathlib-feedstock/pull/3

**Pull request closed without merging**
